security.jwt.secret=please-change-me-to-a-very-long-256-bit-secret
security.jwt.expiryMs=86400000

admin.user.one.email=guanyejun@hotmail.com
admin.user.one.password=!Jerry197981

admin.user.two.email=mijiezhou9@gmail.com
admin.user.two.password=!Gyjai3399